#!/bin/bash

echo 'Have you already installed Sublime Text 3? [Y/N]'

read sublime_input

if [ $sublime_input == 'N' ] || [ $sublime_input == 'n' ]
then
  echo ''
  echo '***** Adding Sublime Text 3 PPA *****'
  echo ''
  sudo add-apt-repository ppa:webupd8team/sublime-text-3
  
  echo ''
  echo '***** Updating system *****'
  echo ''
  sudo apt-get update
  
  echo ''
  echo '***** Installing Sublime Text 3 *****'
  echo ''
  sudo apt-get install -y sublime-text-installer
  
  echo ''
  echo '***** Sublime Text 3 installed successfully *****'
  echo ''
else
  echo ''
  echo '***** Skip installing Sublime Text 3 *****'
  echo ''
fi

echo ''
echo 'Have you already installed Fcitx? [Y/N]'

read fcitx_input

if [ $fcitx_input == 'N' ] || [ $fcitx_input == 'n' ]
then
  
  echo ''
  echo '***** Adding Fcitx PPA *****'
  echo ''
  sudo add-apt-repository ppa:fcitx-team/nightly
  
  echo ''
  echo '***** Updating system *****'
  echo ''
  sudo apt-get update

  echo ''
  echo '***** Installing Fcitx and Pinyin methods *****'
  echo ''
  sudo apt-get install -y fcitx fcitx-config-gtk fcitx-sunpinyin fcitx-googlepinyin fcitx-module-cloudpinyin fcitx-sogoupinyin

  echo ''
  echo '***** Installing Fcitx related libs *****'
  echo ''
  sudo apt-get install -y build-essential libgtk2.0-dev
  sudo apt-get install -y fcitx-table-all
  
  echo ''
  echo '***** Fcitx installed successfully! *****'
  echo ''
  echo '***** Setting Fcitx as the default input method! *****'
  im-switch -s fcitx -z default
else
  echo ''
  echo '***** Skip installing Fcitx *****'
  echo ''
fi

echo ''
echo '***** Adding shared lib to sublime directory *****'
echo ''
echo '***** Checking for existing file *****'
if [ -e '/opt/sublime_text/libsublime-imfix.so']
  then
  sudo cp ./lib/libsublime-imfix.so /opt/sublime_text/
else
  echo ''
  echo '***** libsublime-imfix.so is already existing *****'
fi

echo ''
echo '***** Replacing subl with new one *****'
echo ''
if [ -e 'rm /usr/bin/subl' ]
  then
  sudo rm /usr/bin/subl && sudo cp ./src/subl /usr/bin/
fi

echo ''
echo '***** Sublime Text input method problem fixed! *****'
echo ''

echo ''
echo '***** More......installing addtional skin *****'
echo ''
echo '***** Un-packing skin into current folders *****'
echo ''
tar -zxvf /src/anran.tar.gz

echo '***** Copy skins to Fcitx skin folder: /usr/share/fcitx/skin *****'
echo ''
sudo cp -r anran /usr/share/fcitx/skin/
rm -r anran

echo ''
echo '***** Done! *****'





